server.port=8080
spring.application.name=shareit-gateway

logging.level.org.springframework.web=DEBUG
logging.level.ru.practicum.shareit=DEBUG

spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.jackson.serialization.indent_output=true